name: gpmx
author: axetroy <troy450409405@gmail.com>
description: Git Package Manager, make you manage the repository easier, Power by Dart
homepage: https://github.com/gpmer/gpm.dart
version: 0.2.1
executables:
  gpmx: gpmx
dependencies:
  log: ">=0.0.6 <1.0.0"
  path: ">=1.4.1 <2.0.0"
  prompt: ">=0.1.7 <0.2.0"
  escli:
  git_url_parse: